//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.05 at 05:59:53 PM CEST 
//


package com.politechnika.pkckbinding.dto.rockets;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.rockets package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.rockets
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Mass }
     * 
     */
    public Mass createMass() {
        return new Mass();
    }

    /**
     * Create an instance of {@link Cost }
     * 
     */
    public Cost createCost() {
        return new Cost();
    }

    /**
     * Create an instance of {@link Rockets }
     * 
     */
    public Rockets createRockets() {
        return new Rockets();
    }

    /**
     * Create an instance of {@link Rocket }
     * 
     */
    public Rocket createRocket() {
        return new Rocket();
    }

    /**
     * Create an instance of {@link Thrust }
     * 
     */
    public Thrust createThrust() {
        return new Thrust();
    }

    /**
     * Create an instance of {@link PayloadCapacity }
     * 
     */
    public PayloadCapacity createPayloadCapacity() {
        return new PayloadCapacity();
    }

}
