//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.05 at 05:59:53 PM CEST 
//


package com.politechnika.pkckbinding.dto.rockets;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import lombok.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://example.com/rockets}mass"/>
 *         &lt;element ref="{http://example.com/rockets}thrust" minOccurs="0"/>
 *         &lt;element ref="{http://example.com/rockets}payload_capacity"/>
 *         &lt;element ref="{http://example.com/rockets}cost"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rocket_id" use="required" type="{http://example.com/rockets}rocket_pattern" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "mass",
    "thrust",
    "payloadCapacity",
    "cost"
})
@XmlRootElement(name = "rocket")
public class Rocket {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected Mass mass;
    protected Thrust thrust;
    @XmlElement(name = "payload_capacity", required = true)
    protected PayloadCapacity payloadCapacity;
    @XmlElement(required = true)
    protected Cost cost;
    @XmlAttribute(name = "rocket_id", required = true)
    protected String rocketId;
}
