//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.05 at 05:59:53 PM CEST 
//


package com.politechnika.pkckbinding.dto.flightschedule;

import javax.xml.bind.annotation.*;

import lombok.Data;
import com.politechnika.pkckbinding.dto.customers.Customers;
import com.politechnika.pkckbinding.dto.launchpads.Launchpads;
import com.politechnika.pkckbinding.dto.rockets.Rockets;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}authors"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}launches"/>
 *         &lt;element ref="{http://example.com/launchpads}launchpads"/>
 *         &lt;element ref="{http://example.com/customers}customers"/>
 *         &lt;element ref="{http://example.com/rockets}rockets"/>
 *         &lt;element ref="{}payloads"/>
 *         &lt;element ref="{}locations"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authors",
    "description",
    "launches",
    "launchpads",
    "customers",
    "rockets",
    "payloads",
    "locations"
})
@XmlRootElement(name = "flight_schedule")
public class FlightSchedule {

    @XmlElement(required = true)
    protected Authors authors;
    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected Launches launches;
    @XmlElement(namespace = "http://example.com/launchpads", required = true)
    protected Launchpads launchpads;
    @XmlElement(namespace = "http://example.com/customers", required = true)
    protected Customers customers;
    @XmlElement(namespace = "http://example.com/rockets", required = true)
    protected Rockets rockets;
    @XmlElement(required = true)
    protected Payloads payloads;
    @XmlElement(required = true)
    protected Locations locations;
}
