//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.05 at 05:59:53 PM CEST 
//


package com.politechnika.pkckbinding.dto.flightschedule;

import javax.xml.bind.annotation.*;

import lombok.*;
import com.politechnika.pkckbinding.dto.rockets.Mass;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}payload_type"/>
 *         &lt;element ref="{http://example.com/rockets}mass"/>
 *       &lt;/sequence>
 *       &lt;attribute name="payload_id" use="required" type="{}payload_pattern" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "payloadType",
    "mass"
})
@XmlRootElement(name = "payload")
public class Payload {

    @XmlElement(name = "payload_type", required = true)
    protected PayloadType payloadType;
    @XmlElement(required = true)
    protected Mass mass;
    @XmlAttribute(name = "payload_id", required = true)
    protected String payloadId;
}
